### ISSUE TITLE
Screen return not correctly handled

### ISSUE THREAD

**Issue by mirtouf** [santosh0705/xterm-express#1]
Hi,

I had a test with this software and it seems exiting or detaching a screen session is not correctly handled as the command prompt return is done at the top of the screen input (see the image).
I am running xterm-session through a nginx reverse proxy.
![xterm](https://user-images.githubusercontent.com/5165058/39627065-bae76ac4-4fa4-11e8-8903-ad5f4461b067.PNG)
At least the screen should be cleared if it is not possible to go back at the bottom of the page.

By the way, is the full screen option fully implemented ? Tested with Chrome and FF and nothing happens.

**Comment by santosh0705** [comment]
Thanks @mirtouf for taking time to test and reporting the issue. It look like pseudoterminal is not handled correctly by `node-pty` module. The commands are spawned by `node-pty` module and whatever is received from it is send back to xtermjs. Need to investigate more on this.

Fullscreen was implemented and I had tested on Safari and FF on Mac. In last minute code cleanup it got broken. fixing it soon.
